version: '2'

services:

  angular-mcon:
    build:
      context: .
      dockerfile: ./.docker/angular-mcon.production.dockerfile
    command: npm run build.prod
    container_name: ng2-finance-build-prod
    image: ng2-finance
    networks:
      - prod-network
    volumes:
      - ./dist:/home/app/angular-mcon/dist



networks:
  prod-network:
    driver: bridge
