version: '2'

services:

  ng2-finance:
    build:
      context: .
      dockerfile: ./.docker/ng2-finance.development.dockerfile
    command: npm start
    container_name: ng2-finance-start
    image: ng2-finance
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
