version: '2'

services:

  ng2-finance:
    build:
      context: .
      dockerfile: ./.docker/ng2-finance.production.dockerfile
    command: npm run build.prod
    container_name: ng2-finance-build-prod
    image: ng2-finance
    networks:
      - prod-network
    volumes:
      - ./dist:/home/app/ng2-finance/dist

  ng2-finance-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/ng2-finance.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: ng2-finance-nginx-prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
      - '5555:80'
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/ng2-finance.template
      - ./dist/prod:/var/www/dist/prod

networks:
  prod-network:
    driver: bridge
